freeze pip requirements (SQLAlchemy update breaks search API)
- requirements.txt so far specified Flask_SQLAlchemy and not
  SQLAlchemy directly
- SQLAlchemy now explicitly specified with version 1.2.10.
  Version 1.2.12 breaks canvasindexer/api/views.py:202

        docs = docs.join(assocs).join(terms).all()

  which results in an AttributeError

        'BaseQuery' object has no attribute 'is_clause_element'

  there, but worked fine in all versions before.